Repository CS2103JAN2018-T11-B1/main, pull requests merged in 2018-03, with the labels that each got.

#61 [V1.2][T11-B1] Cho Chih Tun feature contribution
  docs/DeveloperGuide.adoc
  docs/images/AddTuteeCommandSequenceDiagram.png
Labels: developer guide

#62 [V1.2][T11-B1] Cho Chih Tun addtutee feature
  src/main/java/seedu/address/logic/commands/AddTuitionTaskCommand.java
  src/main/java/seedu/address/logic/commands/AddTuteeCommand.java
  src/main/java/seedu/address/logic/parser/AddTuitionTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/AddTuteeCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/personal/PersonalTask.java
  src/main/java/seedu/address/model/tutee/EducationLevel.java
  src/main/java/seedu/address/model/tutee/Grade.java
  src/main/java/seedu/address/model/tutee/School.java
  src/main/java/seedu/address/model/tutee/Subject.java
  src/main/java/seedu/address/model/tutee/TuitionSchedule.java
  src/main/java/seedu/address/model/tutee/TuitionTask.java
  src/main/java/seedu/address/model/tutee/Tutee.java
  src/test/java/seedu/address/logic/parser/AddTuitionTaskCommandParserTest.java
  src/test/java/seedu/address/model/ScheduleTest.java
Labels: status.ongoing, type.enhancement, type.epic

#63 [V1.2][T11-B1] Cho Chih Tun Updates documentation
  README.adoc
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: priority.high

#73 [v1.2][Raymond Zheng] DeleteTuitionTaskCommand
  src/main/java/seedu/address/logic/commands/DeleteTuitionTaskCommand.java
  src/main/java/seedu/address/model/tutee/TuitionSchedule.java
  src/test/java/seedu/address/logic/commands/DeleteTuitionTaskCommandTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
Labels: priority.high, type.enhancement

#89 [V.13][T11-B1] Cho Chih Tun Googel Search Page and fix some errors
  .travis.yml
  build.gradle
  docs/DummySearchPage.html
  docs/UserGuide.adoc
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/test/java/seedu/address/logic/commands/AddPersonalTaskCommandTest.java
Labels: priority.medium, type.enhancement

#95 [V1.3][T11-B1] Cho Chih Tun Integrate CalendarFX
  Collate-GUI.jar
  build.gradle
  collated/functional/ChoChihTun.md
  collated/test/ChoChihTun.md
  docs/UserGuide.adoc
  lib/README-EXT.txt
  lib/calendarfx-recurrence-8.4.0.jar
  lib/calendarfx-view-8.4.0.jar
  lib/controlsfx-8.40.11.jar
  lib/fontawesomefx-commons-8.13.jar
  lib/fontawesomefx-fontawesome-4.7.0-1.jar
  lib/license4j-1.4.0.jar
  src/main/java/seedu/address/logic/commands/AddTuteeCommand.java
  src/main/java/seedu/address/logic/commands/ChangeCommand.java
  src/main/java/seedu/address/logic/parser/AddTuteeCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ChangeCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/exceptions/SameTimeUnitException.java
  src/main/java/seedu/address/model/Schedule.java
  src/main/java/seedu/address/model/person/exceptions/DurationParseException.java
  src/main/java/seedu/address/model/person/exceptions/TimingClashException.java
  src/main/java/seedu/address/model/personal/PersonalTask.java
  src/main/java/seedu/address/model/tutee/EducationLevel.java
  src/main/java/seedu/address/model/tutee/Grade.java
  src/main/java/seedu/address/model/tutee/School.java
  src/main/java/seedu/address/model/tutee/Subject.java
  src/main/java/seedu/address/model/tutee/TuitionTask.java
  src/main/java/seedu/address/model/tutee/Tutee.java
  src/main/java/seedu/address/ui/CalendarPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/CalendarPanel.fxml
  src/main/resources/view/Extensions.css
  src/main/resources/view/MainWindow.fxml
  src/test/java/guitests/guihandles/CalendarPanelHandle.java
  src/test/java/guitests/guihandles/MainWindowHandle.java
  src/test/java/seedu/address/logic/commands/AddTuteeCommandTest.java
  src/test/java/seedu/address/logic/parser/AddPersonalTaskCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddTuitionTaskCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddTuteeCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ChangeCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/ScheduleTest.java
  src/test/java/seedu/address/model/tutee/EducationLevelTest.java
  src/test/java/seedu/address/model/tutee/GradeTest.java
  src/test/java/seedu/address/model/tutee/SchoolTest.java
  src/test/java/seedu/address/model/tutee/SubjectTest.java
  src/test/java/seedu/address/testutil/TuteeBuilder.java
  src/test/java/seedu/address/testutil/TuteeUtil.java
  src/test/java/seedu/address/testutil/TypicalCalendarView.java
  src/test/java/seedu/address/testutil/TypicalTutees.java
  src/test/java/seedu/address/ui/CalendarPanelTest.java
  src/test/java/systemtests/AddTuteeCommandSystemTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
Labels: type.enhancement

#94 [V1.3][T11-B1] Eka Buyung | Find and Sort command (inc. tests and documentation)
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/commands/ViewSortCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/logic/parser/ViewSortCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/PersonSortUtil.java
  src/main/java/seedu/address/model/tutee/EducationLevelContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/tutee/GradeContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/tutee/SchoolContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/tutee/SubjectContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTuteeCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalTutees.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
Labels: type.enhancement

#96 Update UI mock up
  README.adoc
  docs/images/ui-mockup.png
Labels: type.task

#101 Fix panel width
  src/main/resources/view/MainWindow.fxml
Labels: type.task

#103 [V1.4][T11-B1] Cho Chih Tun Fix some errors in the code
  gradle.properties
  src/test/java/seedu/address/logic/commands/AddPersonalTaskCommandTest.java
  src/test/java/systemtests/SystemTestSetupHelper.java
Labels: type.task
