Repository CS2103JAN2018-T11-B1/main, pull requests merged in 2018-04, with the labels that each got.

#104 [V1.4][T11-B1] Cho Chih Tun - add entries to calendar and fix errors
  README.adoc
  collated/functional/ChoChihTun.md
  collated/test/ChoChihTun.md
  docs/images/Ui.png
  docs/images/ui-mockup.png
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/Task.java
  src/main/java/seedu/address/model/personal/PersonalSchedule.java
  src/main/java/seedu/address/model/personal/PersonalTask.java
  src/main/java/seedu/address/model/tutee/TuitionSchedule.java
  src/main/java/seedu/address/model/tutee/TuitionTask.java
  src/main/java/seedu/address/storage/XmlAdaptedTask.java
  src/main/java/seedu/address/storage/XmlSerializableAddressBook.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/main/java/seedu/address/ui/CalendarPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/BrowserPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/guitests/guihandles/CalendarPanelHandle.java
  src/test/java/guitests/guihandles/MainWindowHandle.java
  src/test/java/seedu/address/logic/parser/ChangeCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/personal/PersonalTaskTest.java
  src/test/java/seedu/address/model/tutee/TuitionTaskTest.java
  src/test/java/seedu/address/testutil/TypicalCalendarEntries.java
  src/test/java/seedu/address/testutil/TypicalCalendarView.java
  src/test/java/seedu/address/ui/BrowserPanelTest.java
  src/test/java/seedu/address/ui/CalendarPanelTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
Labels: priority.high, type.enhancement

#105 [V1.4][T11-B1] Eka Buyung | update addtask parsers, delete task, list tutee, find task
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddPersonalTaskCommand.java
  src/main/java/seedu/address/logic/commands/AddTuitionTaskCommand.java
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTuitionTaskCommand.java
  src/main/java/seedu/address/logic/commands/FindPersonCommand.java
  src/main/java/seedu/address/logic/commands/FindTaskCommand.java
  src/main/java/seedu/address/logic/commands/ListTuteeCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AddPersonalTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/AddTuitionTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/FindPersonCommandParser.java
  src/main/java/seedu/address/logic/parser/FindTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UniqueTaskList.java
  src/main/java/seedu/address/model/person/PersonSortUtil.java
  src/main/java/seedu/address/model/personal/PersonalTask.java
  src/main/java/seedu/address/model/task/MonthContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/task/TaskSortUtil.java
  src/main/java/seedu/address/model/task/exceptions/TaskNotFoundException.java
  src/main/java/seedu/address/model/tutee/TuitionTask.java
  src/test/java/seedu/address/logic/commands/FindPersonCommandTest.java
  src/test/java/seedu/address/logic/parser/AddPersonalTaskCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddTuitionTaskCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindPersonCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/address/model/ScheduleTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/FindPersonCommandSystemTest.java
  src/test/java/systemtests/SystemTestSetupHelper.java
Labels: priority.high, type.enhancement

#107 [V1.4][T11-B1] Updates to userguide
  docs/UserGuide.adoc
Labels: type.task

#108 [V1.4][T11-B1] Cho Chih Tun Update README and UserGuide
  README.adoc
  docs/UserGuide.adoc
Labels: type.task

#109 [V1.4][T11-B1] Eka Buyung | Some tests and edit on find task command
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/FindTaskCommand.java
  src/main/java/seedu/address/logic/parser/FindTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/exceptions/InvalidBoundariesException.java
  src/test/java/seedu/address/storage/XmlAdaptedPersonTest.java
  src/test/java/systemtests/ModelHelper.java
Labels: priority.medium, type.enhancement

#115 [v1.5][T11-B1] Cho Chih Tun - refractor scheduling out, integrate calendarFX to deletetask, adjust mainwindow message panel size
  collated/functional/ChoChihTun.md
  collated/functional/ashakra.md
  collated/functional/yungyung04.md
  collated/test/ChoChihTun.md
  collated/test/yungyung04.md
  docs/DeveloperGuide.adoc
  docs/images/AddTuteeCommandSequenceDiagram.PNG
  docs/images/AddTuteeCommandSequenceDiagram.png
  docs/images/TuteeClassDiagram.JPG
  src/main/java/seedu/address/logic/commands/AddPersonalTaskCommand.java
  src/main/java/seedu/address/logic/commands/AddTuitionTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddPersonalTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/AddTuitionTaskCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/Schedule.java
  src/main/java/seedu/address/model/UniqueTaskList.java
  src/main/java/seedu/address/model/person/exceptions/TimingClashException.java
  src/main/java/seedu/address/model/personal/PersonalSchedule.java
  src/main/java/seedu/address/model/personal/PersonalTask.java
  src/main/java/seedu/address/model/tutee/TuitionSchedule.java
  src/main/java/seedu/address/model/tutee/TuitionTask.java
  src/main/java/seedu/address/model/tutee/Tutee.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/AddPersonalTaskCommandTest.java
  src/test/java/seedu/address/model/ScheduleTest.java
  src/test/java/seedu/address/model/UniqueTaskListTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
Labels: priority.high, type.enhancement, type.task

#120 [v1.5rc][T11-B1] Cho Chih Tun - Change main window layout and colours
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/change-d.png
  docs/images/change-m.png
  docs/images/change-w.png
  docs/images/change-y.png
  src/main/java/seedu/address/ui/CalendarPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/MainWindow.fxml
Labels: type.task

#125 [V1.5rc][T11-B1]Eka Buyung Lienadi | setup task test util and add deletetask test
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/AddTuitionTaskCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/Task.java
  src/main/java/seedu/address/model/personal/PersonalTask.java
  src/main/java/seedu/address/model/tutee/TuitionTask.java
  src/main/java/seedu/address/model/tutee/Tutee.java
  src/test/data/XmlSerializableAddressBookTest/typicalPersonsAndTaskAddressBook.xml
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTuteeCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteTuitionTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindPersonCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/RedoCommandTest.java
  src/test/java/seedu/address/logic/commands/SelectCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoableCommandTest.java
  src/test/java/seedu/address/logic/parser/AddPersonalTaskCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddTuitionTaskCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindPersonCommandParserTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/storage/XmlAdaptedPersonTest.java
  src/test/java/seedu/address/storage/XmlAddressBookStorageTest.java
  src/test/java/seedu/address/storage/XmlSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/ModelStub.java
  src/test/java/seedu/address/testutil/TaskBuilder.java
  src/test/java/seedu/address/testutil/TaskUtil.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/typicaladdressbook/TypicalAddressBookCompiler.java
  src/test/java/seedu/address/testutil/typicaladdressbook/TypicalPersons.java
  src/test/java/seedu/address/testutil/typicaladdressbook/TypicalTasks.java
  src/test/java/seedu/address/testutil/typicaladdressbook/TypicalTutees.java
  src/test/java/seedu/address/ui/PersonListPanelTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/AddTuteeCommandSystemTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/ClearCommandSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/FindPersonCommandSystemTest.java
  src/test/java/systemtests/ModelHelper.java
  src/test/java/systemtests/SelectCommandSystemTest.java
Labels: priority.high, type.task

#129 [V1.5rc][T11-B1]Eka Buyung Lienadi | resolve conflict
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/SelectCommand.java
  src/main/java/seedu/address/ui/BrowserPage.java
  src/test/java/seedu/address/logic/commands/AddPersonalTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/testutil/typicaladdressbook/TypicalTasks.java
  src/test/java/seedu/address/ui/BrowserPageTest.java
Labels: priority.medium, type.enhancement

#130 [V1.5rc][T11-B1]Anas Shakra | Collations
  collated/functional/a-shakra.md
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ListTaskCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/UniqueTaskList.java
  src/main/java/seedu/address/storage/XmlAdaptedTask.java
  src/main/java/seedu/address/storage/XmlSerializableAddressBook.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/java/seedu/address/ui/TaskCardListPanel.java
  src/main/resources/view/TaskCardListPanel.fxml
  src/main/resources/view/TaskListCard.fxml
Labels: priority.high, type.task

#135 [V1.5rc][T11-B1] Anas Shakra Updated Developer guide + User Guide + Portfolio + added aliases for sort commands
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/a-shakra.adoc
  docs/team/johndoe.adoc
  src/main/java/seedu/address/logic/commands/SortPersonCommand.java
  src/main/java/seedu/address/logic/commands/SortTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
Labels: priority.high, type.enhancement

#138 [v1.5][T11-B1] Cho Chih Tun - Added findtaskby command test
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/tutee/Grade.java
  src/test/data/XmlAddressBookStorageTest/invalidAndValidPersonAddressBook.xml
  src/test/data/XmlAddressBookStorageTest/invalidPersonAddressBook.xml
  src/test/java/seedu/address/logic/commands/AddTuteeCommandTest.java
  src/test/java/seedu/address/logic/commands/FindTaskCommandTest.java
  src/test/java/seedu/address/logic/parser/AddPersonalTaskCommandParserTest.java
Labels: priority.high, type.task

#139 [v1.5][T11-B1] Cho Chih Tun - Fix edit bugs
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddTuteeCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/tutee/Tutee.java
  src/main/java/seedu/address/storage/XmlAddressBookStorage.java
  src/test/data/XmlAddressBookStorageTest/invalidAndValidPersonAddressBook.xml
  src/test/data/XmlAddressBookStorageTest/invalidPersonAddressBook.xml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/SortPersonCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TuteeBuilder.java
  src/test/java/seedu/address/testutil/typicaladdressbook/TypicalTutees.java
Labels: priority.high, severity.Low, type.task

#144 [v1.5][T11-B1] Cho Chih Tun - Update guides
  docs/AboutUs.adoc
  docs/UserGuide.adoc
Labels: type.task

#146 [v1.5][T11-B1] Cho Chih Tun update guides
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/AddTuteeActivityDiagram.png
Labels: type.task

#150 [v1.5][T11-B1] Cho Chih Tun refractor exception classes into correct directory
  docs/DeveloperGuide.adoc
  docs/team/chochihtun.adoc
  docs/team/johndoe.adoc
  src/main/java/seedu/address/logic/commands/AddPersonalTaskCommand.java
  src/main/java/seedu/address/logic/commands/AddTuitionTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddPersonalTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/AddTuitionTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/exceptions/DurationParseException.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UniqueTaskList.java
  src/main/java/seedu/address/model/person/exceptions/TaskNotFoundException.java
  src/main/java/seedu/address/model/task/exceptions/TimingClashException.java
  src/test/java/seedu/address/logic/commands/AddPersonalTaskCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/UniqueTaskListTest.java
  src/test/java/seedu/address/testutil/AddressBookBuilder.java
  src/test/java/seedu/address/testutil/ModelStub.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
  src/test/java/seedu/address/testutil/typicaladdressbook/TypicalAddressBookCompiler.java
Labels: type.task

#143 [V1.5][T11-B1] Anas Shakra || Sample data util class modified to prepare JAR file
  collated/test/a-shakra.md
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/images/taskStorage.jpg
  docs/team/ashakra.adoc
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/systemtests/SampleDataTest.java
Labels: priority.high, type.task

#151 [v1.5][T11-B1] Cho Chih Tun - Final check edit
  src/main/java/seedu/address/logic/commands/AddTuteeCommand.java
  src/main/java/seedu/address/logic/parser/AddTuteeCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/Task.java
  src/main/java/seedu/address/model/UniqueTaskList.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/person/PersonSortUtil.java
  src/main/java/seedu/address/model/personal/PersonalTask.java
  src/main/java/seedu/address/model/task/TaskSortUtil.java
  src/main/java/seedu/address/model/tutee/Tutee.java
  src/main/java/seedu/address/storage/XmlAdaptedTask.java
  src/test/java/seedu/address/logic/commands/AddTuteeCommandTest.java
  src/test/java/seedu/address/logic/parser/AddTuteeCommandParserTest.java
  src/test/java/seedu/address/model/tutee/EducationLevelContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/tutee/EducationLevelTest.java
  src/test/java/seedu/address/model/tutee/GradeContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/tutee/GradeTest.java
  src/test/java/seedu/address/model/tutee/SchoolTest.java
  src/test/java/seedu/address/testutil/ModelStub.java
  src/test/java/seedu/address/testutil/TaskBuilder.java
  src/test/java/seedu/address/testutil/TaskUtil.java
  src/test/java/seedu/address/testutil/TuteeBuilder.java
  src/test/java/seedu/address/testutil/TypicalCalendarEntries.java
Labels: priority.high, type.task

#153 [v1.5][T11-B1] Cho Chih Tun - update portfolio
  docs/team/chochihtun.adoc
Labels: type.task

#154 [v1.5][T11-B1] Cho Chih Tun - Update userguide & remove select command
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/AddTuteeCommandSystemTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/ClearCommandSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/FindPersonCommandSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
Labels: priority.medium, type.task

#149 [V1.5][T11-B1]Eka Buyung | Glossary, final checks
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/parser/AddPersonalTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/FindTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/UniqueTaskList.java
  src/main/java/seedu/address/model/person/PersonSortUtil.java
  src/main/java/seedu/address/model/personal/PersonalTask.java
  src/main/java/seedu/address/model/task/TaskSortUtil.java
  src/main/java/seedu/address/model/tutee/TuitionTask.java
  src/test/java/seedu/address/logic/parser/AddPersonalTaskCommandParserTest.java
  src/test/java/seedu/address/testutil/typicaladdressbook/TypicalTasks.java
Labels: priority.high, type.task

#159 Collated
  collated/functional/ChoChihTun.md
  collated/functional/ashakra.md
  collated/functional/yungyung04.md
  collated/test/ChoChihTun.md
  collated/test/ashakra.md
  collated/test/yungyung04.md
  src/main/java/seedu/address/storage/XmlAddressBookStorage.java
Labels: priority.high, type.task

#160 Minor edit and collate
  collated/functional/ChoChihTun.md
  collated/functional/a-shakra.md
  collated/functional/ashakra.md
  collated/test/a-shakra.md
  collated/test/ashakra.md
  docs/AboutUs.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/parser/exceptions/SameTimeUnitException.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
Labels: type.task
